# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This contains a utility function that updates the kfp_config file."""

import google.cloud.storage
import yaml
import functools
import copy

_CLOUD_RESOURCES_PATH = "cloud-infrastructure/gcp/cloud-resources.yaml"


@functools.cache
def readYAMLConfig(config_filename: str) -> dict:
    """Read a YAML config file.

    Note that this function uses the functools.cache decorator, so that each
    config file will only be read once per invocation of the Python interpreter.

    Args:
        config_filename (str): Filename of YAML file to be read.

    Returns:
        dict: A dict containing the parsed contents of the YAML file.
    """
    with open(config_filename, "r", encoding="utf-8") as fin:
        return yaml.safe_load(fin)


@functools.cache
def readAndMergeYAMLConfig(
    config_filename: str,
    environment: str | None = None,
) -> dict:
    """Read a YAML config file. If an env is specified, merges the environment
    specific config with the placeholders in the rest of the config.

    Note that this function uses the functools.cache decorator, so that each
    config file will only be read once per invocation of the Python interpreter.

    Args:
        config_filename (str): Filename of YAML file to be read.
        environment (str): The environment to use (e.g., 'prod', 'stage',
            'train').

    Returns:
        dict: The final, merged, and formatted configuration dictionary.
    """
    with open(config_filename, "r", encoding="utf-8") as f:
        full_config = yaml.safe_load(f)

    # Get a deep copy of the common config to avoid modifying it in place
    full_config_copy = copy.deepcopy(full_config)
    # Remove the environment key from the final config
    full_config_copy.pop("environment", None)

    # Get the specific overrides for the chosen environment
    environments_data = full_config.get("environments") or {}
    env_overrides = environments_data.get(environment, {})

    # Merge the overrides into the common config
    final_config = _deep_merge(full_config_copy, env_overrides)

    # Remove environments key as it is no longer needed
    del final_config["environments"]

    return final_config


@functools.cache
def readCloudResourcesConfig(bucket_name: str) -> dict:
    """Read the YAML config file which resides on GCS, containing configuration
    information that was generated by the project factory.

    Note that this function uses the functools.cache decorator, so that each
    config file will only be read once per invocation of the Python interpreter.

    Args:
        bucket_name (str): The bucket in which to search for the YAML file that
            contains the labels of interest.

    Returns:
        dict: A dict containing the parsed contents of the YAML file.
    """
    try:
        # Strip off the scheme, if it's here.
        bucket_name = bucket_name.removeprefix("gs://")

        # Copy the file on GCS to memory.
        client = google.cloud.storage.Client()
        bucket = client.bucket(bucket_name)
        blob = bucket.blob(_CLOUD_RESOURCES_PATH)
        contents = blob.download_as_text()

        # Extract the fields of interest.
        config = yaml.safe_load(contents)

    except Exception as e:
        e.add_note(f"Error reading: gs://{bucket_name}/{_CLOUD_RESOURCES_PATH}")
        raise
    return config


def _deep_merge(base_dict: dict, new_dict: dict) -> dict:
    """
    Recursively merges new_dict into base_dict.

    If a key exists in both and both values are dicts, it merges the sub-dicts.
    Otherwise, the value from new_dict overwrites the value in base_dict.
    """
    for key, value in new_dict.items():
        if (
            isinstance(value, dict)
            and key in base_dict
            and isinstance(base_dict[key], dict)
        ):
            _deep_merge(base_dict[key], value)
        else:
            base_dict[key] = value
    return base_dict


def get_config_value_by_key(config_filename: str, key: str) -> str:
    """Reads a config file and returns the string value for a specific key,
    without using environment merging.

    Args:
        config_filename (str): The path to the YAML configuration file.
        key (str): The top-level key whose value is to be retrieved.

    Returns:
        str: The value associated with the key, converted to a string.
             Returns an empty string if the key or file is not found.
    """
    try:
        config = readYAMLConfig(config_filename)

        value = config.get(key, "")
        return str(value)

    except FileNotFoundError:
        # Note: Error handling should be done in the CLI wrapper to print to stderr.
        # This function returns a sentinel value (empty string)
        return ""
    except Exception:
        # Catch any other parsing errors
        return ""
